### PR TITLE
chore: upgrade Eslint parser to 6.x

### PR DESCRIPTION
**Pull request by philippesic**
* Upgrade eslint parser to 6.x
* Upgrade eslint to 8.48.0

Updates #92

### CODE REVIEW

**Comment by jbinard** [comment]
Can someone take care of this PR? Currently stencil-eslint prevent us from upgrading to latest version of eslint

**Comment by zohon** [comment]
Hi this will be very helpfull to upgrading eslint thanks in advance

**Comment by cmotsn** [comment]
Hi @raphaelpor,

I am tagging you because I am not sure who maintains this repository, but you seem to have been the last person to merge Pull Request...

I am aware that this is a community plugin and that probably nobody is paid to work on it, and so I am only asking whether you have an idea of when you or others would have the time to look at this PR and make a new release, because as others mentioned above, this is preventing us from upgrading eslint. If it won't be merged for months, then we might choose to drop using the plugin (sadly), but if it were just a question or a few weeks, we'll just keep on patiently waiting.

Thank you for any answer, and thank you for your work on this plugin.

**Comment by raphaelpor** [comment]
> Hi @raphaelpor,
> 
> I am tagging you because I am not sure who maintains this repository, but you seem to have been the last person to merge Pull Request...
> 
> I am aware that this is a community plugin and that probably nobody is paid to work on it, and so I am only asking whether you have an idea of when you or others would have the time to look at this PR and make a new release, because as others mentioned above, this is preventing us from upgrading eslint. If it won't be merged for months, then we might choose to drop using the plugin (sadly), but if it were just a question or a few weeks, we'll just keep on patiently waiting.
> 
> Thank you for any answer, and thank you for your work on this plugin.

@cmotsn Thanks for your comments.

I have been busy with other projects but I will spend some time with this, in the coming days.

I just wanna make sure that this is compatible with Stencil V2, before approving it. :)

**Review by raphaelpor — APPROVED** [review]

**Comment by cmotsn** [comment]
Thanks a lot @raphaelpor !
And thanks also to @philippesic for the PR!

**Pull request merged**
