### PR TITLE
Ban default true

### PR DESCRIPTION
**Pull request by ysulyma**
## Pull request checklist

Please check if your PR fulfills the following requirements:
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [ ] Build (`npm run build`) was run locally and any changes were pushed
- [x] Unit tests (`npm test`) were run locally and passed

## Pull request type

 

 

Please check the type of change your PR introduces:
- [ ] Bugfix
- [x] Feature
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [x] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?
In HTML, [boolean attributes always default to `false`](https://html.spec.whatwg.org/multipage/common-microsyntaxes.html#boolean-attributes). For example, we have the attributes `disabled` and `noValidate` instead of `enabled="false"` and `validate="false"`.

This PR adds a rule to enforce similar behavior in Stencil components.

## What is the new behavior?
Added new rule `ban-default-true` to warn about Props which default to `true`.

## Does this introduce a breaking change?

- [x] Yes
- [ ] No

Existing applications would need to change any Props that default to `true`.

## Testing

Added unit tests.

### CODE REVIEW

**Comment by raphaelpor** [comment]
@ysulyma Great addition! 🚀 
Could you please solve the conflicts so we can start reviewing and testing the changes?

**Comment by ysulyma** [comment]
@raphaelpor sorry for late reply, have rebased now!

**Comment by ysulyma** [comment]
@raphaelpor should be fixed now!

**Comment by raphaelpor** [comment]
Thanks for your contribution and patience, @ysulyma. I will proceed with the merge. 🚀

**Pull request merged**
